### PR TITLE
Use Process.MainModule.FileName (which is a path for some reason) sifting instead of window name sifting

### PR DESCRIPTION
**Pull request by ProjectHSI**
Fixes a bug where Cinematic Tools (wrongfully?) injects into the wrong process.

### CODE REVIEW

**Comment by MattFiler** [comment]
does the previous solution not work for you?

**Comment by ProjectHSI** [comment]
I feel like it'd be better to do this way. I'll check if the first solution works.

**Comment by ProjectHSI** [comment]
hold i have to do some extreme debugging because i'm gonna check both of our solutions

**Comment by ProjectHSI** [comment]
Just had a look - the call to Process.GetProcessesByName happens... Too early? The AI.exe process doesn't show up when I break-point LaunchGame.

**Comment by ProjectHSI** [comment]
Planning to push a fix to this so that only the Alien: Isolation process is accounted for.

**Pull request closed without merging**
